"use strict";
exports.__esModule = true;
var punto_1 = require("./punto");
var punto1 = new punto_1.Punto(4, 5);
console.log(punto1.toString());
console.log("------------");
console.log(punto1.distanciaAlOrigen());
console.log("------------");
var punto2 = new punto_1.Punto(6, 8);
console.log(punto1.calcularDistancia(punto2));
console.log("------------");
var puntosAll = [new punto_1.Punto(5, 4), new punto_1.Punto(6, 8), new punto_1.Punto(7, 4), new punto_1.Punto(5, 5)];
console.log(punto1.calcularMasCercano(puntosAll));
